spring:
  application:
    name: rentify-api

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://43.201.87.180:5432/universal_device_rental
    username: deviceRental
    password: rental

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger
    groups-order: desc
    operations-sorter: method
    default-models-expand-depth: -1
  api-docs:
    path: /api-docs

logging:
  level:
    root: INFO
    com.rentify.rentify_api: DEBUG
    org.hibernate.SQL: debug

jwt:
  secret: ${JWT_SECRET}
  access-token-expire-time: 900000
  refresh-token-expire-time: 604800000