spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 5000
      validation-timeout: 2000
      keepalive-time: 300000
      max-lifetime: 1740000

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTH2_GOOGLE_ID}
            client-secret: ${OAUTH2_GOOGLE_SECRET}

logging:
  level:
    root: INFO
    com.rentify.rentify_api: INFO
    org.hibernate.SQL: ERROR

file:
  upload:
    path: ${FILE_UPLOAD_PATH:/app/uploads}
  base:
    url: ${FILE_BASE_URL}