spring:
  application:
    name: rentify-api

  profiles:
    active: local

  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        javax.persistence.validation.mode: none

  datasource:
    driver-class-name: org.postgresql.Driver

  security:
    oauth2:
      client:
        registration:
          google:
            scope:
              - email
              - profile

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger
    groups-order: desc
    operations-sorter: method
    default-models-expand-depth: -1
  api-docs:
    path: /api-docs

jwt:
  secret: ${JWT_SECRET}
  access-token-expire-time: 900000
  refresh-token-expire-time: 604800000

file:
  upload:
    path: ${FILE_UPLOAD_PATH}
  base:
    url: ${FILE_BASE_URL}